language: python

python:
  - "3.8"
env:
  - DJANGO_VERSION=3.0.4 DB=sql_server
install:
  - pip install -q Django==$DJANGO_VERSION
  - pipenv install
# command to run tests
script: 
  - python manage.py test
